"""Shared analytics thresholds with explicit, testable semantics."""

SHORT_GAME_THRESHOLD_SECONDS = 300
DEFAULT_INCLUDE_SHORT_GAMES = False
CHECKPOINT_MINUTES = (5, 10, 15, 20)
CHECKPOINT_TOLERANCE_MS = 90_000
LANE_GOLD_LEAD_THRESHOLD = 500
TEAM_GOLD_LEAD_THRESHOLD = 1_000
