"""Central design tokens and desktop presentation for LoL Analytics."""
from __future__ import annotations
import streamlit as st

APP_TITLE = "LoL Analytics"
APP_SUBTITLE = "Votre historique. Un autre regard sur la partie."
GOLD = "#d6b981"
TEAL = "#58d9c2"
GREEN = "#70ddb0"
RED = "#f28b99"
MUTED = "#9aaec2"

CUSTOM_CSS = """
<style>
:root{--la-bg:#0b1018;--la-surface:#131c28;--la-surface-2:#192433;--la-border:#283648;--la-cyan:#58d9c2;--la-gold:#d6b981;--la-text:#edf3fa;--la-muted:#9aaec2;--la-win:#70ddb0;--la-loss:#f28b99;--la-radius:14px;}
html,body,.stApp,button,input,textarea{font-family:'Segoe UI',sans-serif;}
.stApp{background:radial-gradient(ellipse at 90% 0%,#162333 0%,transparent 45%),var(--la-bg);color:var(--la-text);}
[data-testid=stHeader]{background:rgba(11,16,24,.92);}
[data-testid=stSidebar]{background:#101722;border-right:1px solid var(--la-border);}
[data-testid=stSidebarNav]{padding-top:.2rem;}[data-testid=stSidebarNav] a{border-radius:8px;margin:2px 0;}[data-testid=stSidebarNav] a[aria-current=page]{background:rgba(88,217,194,.12);border-left:2px solid var(--la-cyan);}[data-testid=stSidebarNav] span{font-size:.88rem;}
.block-container{padding:4.5rem 2.5rem 3rem;max-width:1480px;}
h1,h2,h3,h4{font-family:'Segoe UI',sans-serif!important;letter-spacing:-.035em!important;}h2{font-size:1.5rem!important;}h3{font-size:1.15rem!important;}
.la-page-header{margin:.4rem 0 1.35rem;}.la-page-header h1{font-size:2.25rem;line-height:1.16;font-weight:720;padding:.2rem 0 .45rem;margin:0;}.la-page-header p{color:var(--la-muted);font-size:.93rem;margin:0;line-height:1.6;}
.la-eyebrow{font-size:.68rem;color:var(--la-gold);font-weight:700;letter-spacing:.15em;text-transform:uppercase;}.la-muted,.la-meta{color:var(--la-muted);}.la-meta{font-size:.85rem;line-height:1.6;}.la-section-copy{color:var(--la-muted);font-size:.87rem;margin:-.4rem 0 .85rem;}
.la-scope{display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap;padding:.6rem 0 .9rem;color:#c5d2df;font-size:.8rem;}.la-scope b{color:var(--la-cyan);font-variant-numeric:tabular-nums;}.la-scope small{color:var(--la-muted);}
.la-stats{display:grid;grid-template-columns:repeat(var(--stat-cols,4),minmax(0,1fr));gap:.75rem;margin:.65rem 0 1.1rem;}.la-stat{background:var(--la-surface);border:1px solid var(--la-border);border-radius:var(--la-radius);padding:1rem 1.15rem;min-width:0;}.la-stat small,.la-stat-strip small{display:block;color:var(--la-muted);font-size:.75rem;line-height:1.5;}.la-stat strong{display:block;font-size:clamp(1.2rem,2.1vw,1.9rem);font-weight:650;letter-spacing:-.035em;margin-top:.3rem;line-height:1.3;overflow-wrap:anywhere;}
.la-stat-strip{display:flex;gap:1.5rem;flex-wrap:wrap;padding:.85rem 0;border-top:1px solid var(--la-border);border-bottom:1px solid var(--la-border);margin:.8rem 0 1rem;}.la-stat-strip>div{flex:1;min-width:85px;}.la-stat-strip strong{display:block;font-size:1.15rem;margin-top:.3rem;font-weight:650;}
[data-testid=stMetric]{background:var(--la-surface);border:1px solid var(--la-border);border-radius:var(--la-radius);padding:.9rem 1rem;}[data-testid=stMetricValue]{font-size:1.75rem;color:var(--la-text);}[data-testid=stMetricLabel]{color:var(--la-muted);font-size:.8rem;}
.la-hero{padding:1.25rem 1.4rem;border:1px solid var(--la-border);border-radius:var(--la-radius);background:var(--la-surface);}
.la-profile-hero{display:grid;grid-template-columns:1.25fr 1fr;gap:2rem;padding:1.8rem 2rem;border:1px solid #394753;border-radius:18px;overflow:hidden;background-size:cover;background-position:right 22%;margin:.35rem 0 1.1rem;}.la-profile-hero h1{font-size:clamp(2rem,3.2vw,3.3rem);font-weight:720;line-height:1.1;margin:.6rem 0 .8rem;overflow-wrap:anywhere;}.la-profile-hero p{color:#c5d2df;font-size:.85rem;margin:0;}.la-hero-aside{align-self:end;text-align:right;}.la-hero-aside strong{display:block;font-size:1.9rem;letter-spacing:-.02em;}.la-hero-aside small{color:var(--la-muted);}
.la-form{margin:1rem 0 0;}.la-form>small{color:var(--la-muted);font-size:.73rem;}.la-form>div{display:flex;flex-wrap:wrap;gap:.3rem;margin-top:.45rem;}.la-form span{display:inline-flex;align-items:center;justify-content:center;width:27px;height:27px;border-radius:6px;font-size:.72rem;font-weight:750;}.la-form-win{color:var(--la-win);background:rgba(112,221,176,.15);border:1px solid rgba(112,221,176,.25);}.la-form-loss{color:var(--la-loss);background:rgba(242,139,153,.10);border:1px solid rgba(242,139,153,.22);}
.la-insight-card,.la-discovery{background:var(--la-surface);border:1px solid var(--la-border);border-radius:var(--la-radius);padding:1.1rem 1.25rem;min-height:120px;}.la-insight-value{font-size:1.6rem;font-weight:680;color:var(--la-text);margin:.45rem 0;letter-spacing:-.025em;}.la-discovery{border-top:2px solid var(--la-cyan);margin:.35rem 0 .7rem;}.la-discovery-gap{font-size:2rem;letter-spacing:-.04em;font-weight:700;margin:.5rem 0 .65rem;}.la-discovery-gap small{font-size:.85rem;font-weight:400;letter-spacing:0;color:var(--la-muted);}.la-compare-line{display:flex;justify-content:space-between;gap:.75rem;font-size:.85rem;margin:.4rem 0;}.la-discovery footer{color:var(--la-muted);font-size:.7rem;margin-top:.8rem;border-top:1px solid var(--la-border);padding-top:.7rem;}.la-accent-gold{border-top:2px solid var(--la-gold);}.la-accent-green{border-top:2px solid var(--la-win);}
.la-champion-card{border:1px solid var(--la-border);border-radius:12px;padding:.8rem;min-height:150px;background:var(--la-surface);overflow:hidden;}.la-champion-portrait{width:52px;height:52px;object-fit:cover;border-radius:10px;margin-bottom:.5rem;}.la-portrait-fallback{display:block;background:var(--la-surface-2);}.la-champion-name{font-size:.95rem;font-weight:650;color:var(--la-text);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}.la-champion-games{font-size:.75rem;color:var(--la-gold);margin:.3rem 0;}.la-champion-stats{font-size:.76rem;color:var(--la-muted);line-height:1.6;}
.la-champion-hero,.la-match-hero{min-height:210px;padding:1.6rem 2rem;border-radius:16px;margin:.75rem 0 1rem;background-size:cover;background-position:center 25%;border:1px solid #3d4149;display:flex;flex-direction:column;justify-content:flex-end;}.la-display-title{font-size:clamp(2rem,3.2vw,3rem);font-weight:730;line-height:1.05;letter-spacing:-.04em;margin:.5rem 0 .8rem;}.la-hero-stats{display:flex;flex-wrap:wrap;gap:.6rem 1.5rem;font-size:.85rem;color:#c2cedb;}.la-hero-stats b{color:var(--la-text);}.la-title{font-size:2rem;font-weight:700;margin:.4rem 0;}.la-match-hero .la-title span{font-size:1rem;margin-left:.6rem;}
.la-match-row{display:grid;grid-template-columns:42px 1.2fr .85fr .8fr 1.1fr;align-items:center;gap:.9rem;padding:.75rem 1rem;background:var(--la-surface);border:1px solid var(--la-border);border-left:3px solid var(--la-border);border-radius:10px;min-height:78px;}.la-match-row img{width:42px;height:42px;border-radius:8px;}.la-match-row b{display:block;font-size:.82rem;font-weight:650;}.la-match-row small{display:block;font-size:.7rem;color:var(--la-muted);margin-top:.2rem;}.la-result-win{border-left-color:var(--la-win);}.la-result-loss{border-left-color:var(--la-loss);}.la-win{color:var(--la-win);font-weight:650;}.la-loss{color:var(--la-loss);font-weight:650;}.la-match-title{font-weight:650;}.la-match-meta{font-size:.78rem;color:var(--la-muted);}
.la-item-strip{display:flex;flex-wrap:wrap;gap:.55rem;margin:.4rem 0 .7rem;}.la-item{display:inline-flex;align-items:center;gap:.4rem;color:#c9d5e2;font-size:.72rem;max-width:220px;}.la-item img{width:40px;height:40px;border-radius:8px;border:1px solid #49505a;}.la-item-fallback{min-height:40px;padding:.3rem;border:1px solid var(--la-border);border-radius:8px;}.la-item-icon img{width:46px;height:46px;}.la-item-icon span{display:none;}
.la-purchase-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.5rem;}.la-purchase{display:flex;align-items:center;gap:.65rem;padding:.6rem;background:var(--la-surface);border:1px solid var(--la-border);border-radius:10px;}.la-purchase img{width:38px;height:38px;border-radius:7px;}.la-purchase b,.la-purchase span{display:block;}.la-purchase span{color:var(--la-muted);font-size:.73rem;}
.la-chips{display:flex;flex-wrap:wrap;gap:.4rem;margin:.5rem 0 1rem;}.la-chips span,.la-status{padding:.3rem .6rem;border-radius:6px;font-size:.74rem;background:var(--la-surface-2);color:#b8e5dc;border:1px solid var(--la-border);}
.la-export-card{padding:1.7rem 2rem;border:1px solid #625742;border-radius:18px;background:linear-gradient(120deg,#222830,#142128);margin:.5rem 0 1rem;}.la-export-checks{display:flex;gap:.7rem 1.3rem;flex-wrap:wrap;color:var(--la-win);font-size:.78rem;margin-top:1rem;}
.la-build-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.5rem;}.la-build-stats span{padding:.4rem .5rem;border-left:1px solid var(--la-border);}.la-build-stats small{display:block;color:var(--la-muted);font-size:.7rem;}.la-build-stats b{display:block;font-size:1rem;margin-top:.2rem;white-space:nowrap;}
.la-empty{padding:2rem;border:1px dashed #3c4c60;border-radius:16px;background:rgba(19,28,40,.6);margin:1rem 0;}.la-empty h3{margin:.6rem 0;}.la-empty p{color:var(--la-muted);max-width:650px;line-height:1.7;}
.la-brand{display:flex;align-items:center;gap:.7rem;margin-bottom:.7rem;}.la-brand-mark{display:grid;place-items:center;width:32px;height:36px;border:1px solid var(--la-gold);border-radius:9px;color:var(--la-gold);font-weight:750;font-size:.85rem;}.la-brand b{font-size:.93rem;letter-spacing:-.02em;}.la-brand small{display:block;color:var(--la-muted);font-size:.65rem;letter-spacing:.1em;}
.la-library{padding:.8rem;background:var(--la-surface);border:1px solid var(--la-border);border-radius:10px;margin:.7rem 0;}.la-library b{font-size:1.1rem;}.la-library small{display:block;color:var(--la-muted);font-size:.72rem;margin-top:.3rem;}.la-profile-chip{font-size:.8rem;padding:.45rem .7rem;border-radius:8px;background:var(--la-surface-2);border:1px solid var(--la-border);color:var(--la-muted);margin-bottom:.5rem;}.la-profile-chip b{color:var(--la-text);}
[data-testid=stDataFrame]{border:1px solid var(--la-border);border-radius:10px;overflow:hidden;}[data-testid=stExpander]{border-color:var(--la-border);border-radius:10px;}[data-testid=stButton] button,[data-testid=stDownloadButton] button,[data-testid=stFormSubmitButton] button{border-radius:9px;min-height:2.55rem;font-weight:600;}
button:focus-visible,a:focus-visible,input:focus-visible{outline:2px solid var(--la-cyan)!important;outline-offset:3px;}[data-baseweb=tab-list]{gap:1.5rem;}[data-baseweb=tab]{font-size:.85rem;padding-bottom:.75rem;}hr{border-color:var(--la-border)!important;}
button[kind=primary],button[kind=primary] p,button[kind=primaryFormSubmit],button[kind=primaryFormSubmit] p{color:#0b1018!important;}
button[kind=primary]:disabled,button[kind=primary]:disabled p,button[kind=primaryFormSubmit]:disabled,button[kind=primaryFormSubmit]:disabled p{color:var(--la-muted)!important;}
@media(max-width:1400px){.block-container{padding:4.5rem 1.7rem 3rem;}.la-profile-hero{padding:1.5rem;gap:1rem;}.la-match-row{gap:.6rem;padding:.7rem;}.la-stat{padding:.85rem;}.la-page-header h1{font-size:2rem;}}
@media(max-width:1000px){.la-stats{grid-template-columns:repeat(3,minmax(0,1fr));}.la-profile-hero{grid-template-columns:1fr;}.la-hero-aside{text-align:left;}.la-match-row{grid-template-columns:36px 1.2fr 1fr 1fr;}.la-match-row>div:last-child{display:none;}.la-purchase-grid{grid-template-columns:1fr;}}
.la-review-hero{display:flex;justify-content:space-between;gap:1.5rem;align-items:center;border:1px solid #3e544f;border-radius:16px;padding:1.2rem 1.5rem;margin:.5rem 0 1.3rem;background:linear-gradient(115deg,#17282c,#141c28 75%);}.la-review-hero h2{font-size:1.3rem!important;margin:.45rem 0;}.la-review-hero h2 span{color:var(--la-muted);font-weight:400;font-size:.95rem;}.la-review-hero p{margin:.4rem 0;color:#d9e6ed;}.la-review-hero small{color:var(--la-muted);font-size:.75rem;}.la-review-score{text-align:right;min-width:200px;}.la-review-score strong{font-size:2.5rem;font-weight:700;letter-spacing:-.06em;display:block;}.la-review-score small{display:block;}
.la-review-date{font-size:1.25rem;font-weight:650;margin:.65rem 0;}.la-review-date span{color:var(--la-muted);font-weight:400;}.la-review-game{background:var(--la-surface);border:1px solid var(--la-border);border-left:3px solid var(--la-border);border-radius:12px;padding:.85rem .95rem;min-height:239px;margin:0 0 .5rem;}.la-review-game.la-result-win{border-left-color:var(--la-win);}.la-review-game.la-result-loss{border-left-color:var(--la-loss);}.la-review-game header{display:flex;justify-content:space-between;font-size:.68rem;letter-spacing:.04em;color:var(--la-muted);}.la-review-champion{display:flex;gap:.65rem;align-items:center;margin:.8rem 0;}.la-review-champion b{font-size:1rem;overflow-wrap:anywhere;}.la-review-champion small,.la-review-game footer small{display:block;}.la-review-portrait{width:42px;height:42px;border-radius:9px;object-fit:cover;flex-shrink:0;}.la-review-kda{font-size:1.55rem;font-weight:650;letter-spacing:-.03em;}.la-review-game small{color:var(--la-muted);font-size:.73rem;}.la-review-game footer{margin-top:.75rem;padding-top:.6rem;border-top:1px solid var(--la-border);font-size:.76rem;line-height:1.75;}.la-review-game footer span{display:flex;justify-content:space-between;}.la-review-focus{outline:2px solid var(--la-cyan);outline-offset:2px;}.la-review-observation{display:flex;gap:.8rem;padding:.7rem 0;border-bottom:1px solid var(--la-border);font-size:.86rem;line-height:1.6;}.la-review-observation>span{color:var(--la-cyan);}.la-review-observation small{color:var(--la-muted);white-space:nowrap;margin-left:.5rem;}
.la-review-single{display:flex;flex-wrap:wrap;gap:1rem 2rem;align-items:center;min-height:150px;}.la-review-single header{width:100%;}.la-review-single .la-review-champion{flex:1;min-width:150px;}.la-review-single footer{flex:1;min-width:200px;margin:0;border-top:0;border-left:1px solid var(--la-border);padding:.4rem 0 .4rem 1rem;}
@media(max-width:900px){.la-review-hero{align-items:flex-start;flex-direction:column;}.la-review-score{text-align:left;}.la-review-game{min-height:0;}}
/* V2.4: intentional component classes; no generated CSS names or nth-child. */
:root{--la-surface-raised:#1b2939;--la-border-light:#3e5265;--la-space-xs:.25rem;--la-space-sm:.5rem;--la-space-md:1rem;--la-space-lg:1.5rem;--la-space-xl:2rem;--la-shadow:0 12px 32px #00000024;}
.la-page-header{border-left:2px solid var(--la-gold);padding-left:1rem;}.la-page-header .la-eyebrow{margin-bottom:.3rem;}
.la-stat,.la-insight-card,.la-discovery,.la-champion-card,.la-review-game{background:linear-gradient(135deg,#192737,#121b27 80%);box-shadow:inset 0 1px 0 #ffffff05,var(--la-shadow);transition:transform 160ms ease,border-color 160ms ease;}
.la-champion-card:hover,.la-review-game:hover,.la-discovery:hover{border-color:var(--la-border-light);transform:translateY(-2px);}
.la-stat-strip{border:1px solid var(--la-border);border-radius:12px;padding:1rem 1.2rem;background:linear-gradient(110deg,#152431,#121b26);}
.la-profile-hero,.la-champion-hero,.la-match-hero{box-shadow:0 16px 44px #00000038,inset 0 1px 0 #d6b98124;}
.la-review-hero{background:radial-gradient(ellipse at 85% 20%,#204345 0,transparent 65%),linear-gradient(120deg,#1d2e3a,#151d2a);box-shadow:var(--la-shadow);border-color:#4c625e;}
.la-profile-chip{display:inline-block;background:#101c29;border-color:#2d4355;border-radius:30px;padding:.45rem .9rem;}
.la-badge{display:inline-flex;align-items:center;gap:.25rem;border:1px solid var(--la-border-light);border-radius:5px;padding:.18rem .4rem;font-size:.65rem;line-height:1.3;color:#bdd0df;background:#1b2936;white-space:normal;}.la-badge-gold{color:#ead1a1;background:#322e24;border-color:#66593e;}
.la-portrait{display:inline-flex;flex:none;width:60px;height:60px;align-items:center;justify-content:center;overflow:hidden;border:1px solid #64717b;border-radius:12px;background:#253647;color:var(--la-gold);vertical-align:middle;}.la-portrait img{width:100%;height:100%;object-fit:cover;transition:transform 160ms ease;}.la-portrait:hover img{transform:scale(1.055);}.la-portrait-small{width:34px;height:34px;border-radius:8px;}.la-portrait-mini{width:23px;height:23px;border-radius:5px;border-color:#34495b;}.la-portrait-opponent{width:74px;height:74px;border-color:#a58b5e;border-radius:14px;box-shadow:0 6px 18px #0005;}
.la-inventory{display:flex;align-items:center;gap:4px;}.la-inventory-slot{width:30px;height:30px;display:inline-flex;flex:none;align-items:center;justify-content:center;border-radius:6px;border:1px solid #43576c;background:#0e1823;color:var(--la-muted);font-size:.55rem;overflow:hidden;}.la-inventory-slot img{width:100%;height:100%;object-fit:cover;transition:transform 160ms ease;}.la-inventory-slot:hover{border-color:var(--la-gold);}.la-inventory-slot:hover img{transform:scale(1.07);}.la-trinket{margin-left:5px;border-color:#837450;border-radius:50%;}
[class*="st-key-history_card_"].stVerticalBlock{border-color:#304255!important;border-radius:12px!important;padding:.75rem 1rem .35rem!important;background:linear-gradient(110deg,#182838,#121c28 75%);box-shadow:0 6px 20px #00000020;gap:.35rem;transition:border-color 160ms ease,box-shadow 160ms ease;}
[class*="st-key-history_card_"].stVerticalBlock:hover{border-color:#49627a!important;box-shadow:0 9px 24px #00000030;}
.la-history-row{display:grid;grid-template-columns:105px 1.2fr 1fr 1.45fr 140px;align-items:center;gap:1rem;border-left:3px solid #6c7d91;padding:.4rem 0 .4rem .9rem;min-height:88px;}.la-history-win{border-left-color:var(--la-win);}.la-history-loss{border-left-color:var(--la-loss);}.la-history-row small{display:block;font-size:.69rem;color:#a6b9cb;line-height:1.65;}.la-history-result>b{font-size:.86rem;letter-spacing:.09em;}.la-history-champion{display:flex;align-items:center;gap:.65rem;min-width:0;}.la-history-champion b{font-size:.92rem;}.la-history-kda strong{display:block;font-size:1.15rem;font-weight:650;white-space:nowrap;font-variant-numeric:tabular-nums;}.la-history-build small{margin-top:.5rem;}.la-history-encounter>span{display:flex;gap:3px;margin-bottom:4px;}.la-history-encounter small{margin-top:.35rem;}.la-history-result .la-badge{font-size:.58rem;margin-top:.25rem;}
.la-team-heading{font-size:.8rem;letter-spacing:.08em;text-transform:uppercase;color:var(--la-gold);margin:.3rem 0 .75rem;padding-bottom:.5rem;border-bottom:1px solid var(--la-border);}
.la-matchup-card{position:relative;overflow:hidden;border:1px solid #354b5e;border-radius:15px;padding:1.2rem;background:radial-gradient(ellipse at 90% 0%,#304337,transparent 60%),linear-gradient(140deg,#1a2c3d,#131d2b);box-shadow:var(--la-shadow);margin:.2rem 0 .7rem;transition:transform 160ms ease,border-color 160ms ease;}.la-matchup-card:hover{transform:translateY(-2px);border-color:#877853;}.la-matchup-versus{display:flex;gap:.8rem;align-items:center;justify-content:flex-end;margin-bottom:.5rem;}.la-matchup-versus>span:not(.la-portrait){font-size:.63rem;font-weight:750;color:var(--la-gold);letter-spacing:.14em;}.la-matchup-card>small{font-size:.73rem;color:var(--la-muted);}.la-matchup-card h3{margin:.15rem 0!important;font-size:1.4rem!important;padding:0;}.la-matchup-value{font-size:2.1rem;font-weight:700;letter-spacing:-.05em;margin:.5rem 0 .1rem;color:#e5f3ed;}.la-matchup-card footer{display:flex;gap:.5rem;align-items:center;justify-content:space-between;border-top:1px solid #394b56;padding-top:.8rem;margin-top:.9rem;font-size:.76rem;}.la-matchup-legend{display:flex;gap:.65rem;flex-wrap:wrap;margin:.75rem 0;}
[class*="st-key-contexts_mate_card_"].stVerticalBlock{background:linear-gradient(145deg,#1c2d3d,#121c27);border-color:#3d4f61!important;box-shadow:var(--la-shadow);}.la-mate-card h3{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin:.6rem 0 .8rem;padding:0;font-size:1.15rem!important;}.la-mate-portraits{display:flex;gap:.4rem;}.la-mate-stats{display:flex;gap:1.5rem;padding:1rem 0;}.la-mate-stats strong{font-size:1.5rem;font-weight:650;}.la-mate-stats small,.la-mate-card>small{display:block;font-size:.7rem;font-weight:400;color:var(--la-muted);}.la-player-dialog h2{overflow-wrap:anywhere;}
@media(max-width:1450px){.la-history-row{grid-template-columns:86px 1.05fr .95fr 1.35fr 122px;gap:.65rem;padding-left:.6rem;}.la-history-champion>.la-portrait{width:48px;height:48px;}.la-inventory-slot{width:25px;height:25px;}.la-inventory{gap:3px;}.la-portrait-mini{width:21px;height:21px;}.la-history-kda strong{font-size:1rem;}}
@media(max-width:1200px){.la-history-row{grid-template-columns:80px 1fr 1fr 1.3fr;}.la-history-encounter{grid-column:2/-1;display:flex;align-items:center;gap:.7rem;}.la-history-encounter>span{margin:0;}.la-history-encounter small{margin:0;}.la-matchup-versus{gap:.5rem;}}
@media(max-width:750px){.la-history-row{grid-template-columns:80px 1fr;}.la-history-build{grid-column:2;}.la-history-encounter{grid-column:1/-1;flex-wrap:wrap;}.la-history-kda{grid-column:1;}.la-matchup-card{padding:1rem;}}
.la-matchup-card>header{display:flex;align-items:center;justify-content:space-between;gap:.6rem;}.la-matchup-card>header small{color:var(--la-muted);font-size:.7rem;}.la-matchup-card>header h3{font-size:1.1rem!important;}.la-matchup-card>header .la-matchup-versus{gap:.35rem;margin:0;}.la-matchup-card>header .la-portrait-small{width:28px;height:28px;}.la-matchup-card>header .la-portrait-opponent{width:56px;height:56px;}
[class*="st-key-build_inventory_card_"].stVerticalBlock{background:linear-gradient(130deg,#1c2b39,#151f2b);border-color:#485549!important;border-top:2px solid #aa9063!important;box-shadow:var(--la-shadow);}
@media(max-width:1400px){.block-container{padding-top:3.6rem;}.la-page-header{margin:.3rem 0 .8rem;}.la-page-header h1{font-size:1.85rem;}.la-page-header p{font-size:.84rem;}.la-review-hero{padding:.9rem 1.2rem;margin-bottom:.7rem;}.la-review-hero .la-review-score strong{font-size:2.1rem;}.la-scope{padding:.3rem 0 .5rem;}}
/* V2.4.1: native compact roster actions; identity stays in accessible tooltip. */
.la-history-row{grid-template-columns:85px minmax(0,1fr);gap:.65rem .9rem;min-height:150px;}.la-history-kda{grid-column:1;}.la-history-build{grid-column:2;}.la-history-encounter{grid-column:1/-1;}.la-history-encounter small{margin:0;}.la-history-champion>.la-portrait{width:42px;height:42px;border-radius:9px;}
.la-roster-heading{font-size:.67rem;color:var(--la-gold);letter-spacing:.05em;text-transform:uppercase;padding:0 0 .4rem;border-bottom:1px solid var(--la-border);margin-bottom:.25rem;}
[class*="st-key-history_roster_"] [data-testid=stButton] button{min-height:27px;height:27px;padding:1px 3px;justify-content:flex-start;border-radius:5px;}
[class*="st-key-history_roster_"] [data-testid=stButton] button p{font-size:.76rem;font-weight:450;line-height:23px;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
[class*="st-key-history_roster_"] [data-testid=stButton] button img{width:22px;height:22px;max-height:22px;border-radius:5px;margin-right:4px;vertical-align:middle;}
[class*="st-key-history_roster_"] [data-testid=stButton] button:hover{background:#294052;color:#e1f5ef;}
[class*="st-key-history_roster_"] [data-testid=stMarkdownContainer]{margin-bottom:0;}
[class*="st-key-history_roster_"] [data-testid=stButton] button>div{width:100%;min-width:0;justify-content:flex-start;}
[class*="st-key-history_roster_"] [data-testid=stButton] button>div>span{width:100%;min-width:0;overflow:hidden;justify-content:flex-start;}
[class*="st-key-history_roster_"] [data-testid=stButton] [data-testid=stMarkdownContainer]{width:100%;min-width:0;}
[class*="st-key-history_roster_"] [data-testid=stButton] button p{display:block;margin:0;}
.la-roster-own{display:flex;align-items:center;gap:6px;height:27px;padding:1px 3px;font-size:.76rem;color:#d2e8e2;background:#24403866;border-radius:5px;min-width:0;}.la-roster-own>span:last-child{overflow:hidden;white-space:nowrap;text-overflow:ellipsis;}.la-roster-own .la-portrait-mini{width:22px;height:22px;}.la-roster-score{padding-left:31px;font-size:.65rem;color:var(--la-muted);height:21px;}
@media(max-width:750px){.la-history-row{grid-template-columns:85px minmax(0,1fr);}.la-history-build{grid-column:2;}}
@media(prefers-reduced-motion:reduce){*{transition:none!important;animation:none!important;}}
.la-champion-hero-compact{min-height:132px;padding:1rem 1.3rem;margin:.4rem 0 .7rem;gap:.65rem;}
.la-home-hero{padding:1rem 1.5rem;gap:1rem;margin:.35rem 0 .6rem;}
.la-home-hero h1{font-size:clamp(1.7rem,2.6vw,2.5rem);padding:.3rem 0;margin:.35rem 0 .5rem;}
.la-home-hero .la-hero-aside strong{font-size:1.5rem;}
.la-champion-heading{display:flex;align-items:center;gap:.8rem;}.la-champion-heading .la-champion-portrait{margin:0;width:50px;height:50px;}
.la-champion-hero-compact .la-display-title{font-size:clamp(1.6rem,2.5vw,2.2rem);margin:.3rem 0 0;}
.la-champion-hero-compact .la-hero-stats{font-size:.8rem;gap:.4rem 1.2rem;}
@media(max-width:750px){.la-champion-hero-compact{padding:.9rem;}.la-champion-hero-compact .la-hero-stats{gap:.4rem .7rem;}}
</style>
"""


def apply_theme() -> None:
    st.markdown(CUSTOM_CSS, unsafe_allow_html=True)
